//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace angularjs_aspnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string k_name { get; set; }
        public Nullable<double> p_price { get; set; }
        public Nullable<int> kdv { get; set; }
        public Nullable<int> stok { get; set; }
    }
}
